larger-application- exemple/myproject/models.py
#MODELS.PY
# set up db inside the __init__.py under myproject folder
from myproject import db

class Cat(db.Model):

    __tablename__ = 'cats'

    id = db.Column(db.Integer,primary_key=True)
    name = db.Column(db.Text)
    owner = db.relationship('Owner',backref='cat',uselist=False)

    def __init__(self,name):
        self.name = name

    def __repr__(self):
        if self.owner:
            return f"Cat name is {self.name} and owner is {self.owner.name}"
        else:
            return f"Cat name is {self.name} and no owner yet!"

class Owner(db.Model):

    __tablename__ = 'owners'

    id = db.Column(db.Integer,primary_key=True)
    name = db.Column(db.Text)

    cat_id = db.Column(db.Integer,db.ForeignKey('cats.id'))

    def __init__(self,name,cat_id):
        self.name = name
        self.cat_id = cat_id

larger-application- exemple/myproject/cats/forms.py
# forms.py cats
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField

class AddForm(FlaskForm):

    name = StringField('Name of Cat:')
    submit = SubmitField('Add Cat')

class DelForm(FlaskForm):

    id = IntegerField("Id Number of Cat to Remove: ")
    submit = SubmitField("Remove Cat")

larger-application- exemple/myproject/owners/forms.py
# owners folder --> forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField

class AddForm(FlaskForm):

    name = StringField('Name of Owner:')
    car_id = IntegerField('Id of Cat:')
    submit = SubmitField('Add Owner')

larger-application- exemple/myproject/__init__.py
# __init__.py underneath myproject folder

import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

app = Flask(__name__)

app.config['SECRET_KEY'] = 'mysecretkey'
basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///'+os.path.join(basedir,'data')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
Migrate(app,db)

from myproject.cats.views import cats_blueprint
from myproject.owners.views import owners_blueprints

app.register_blueprint(owners_blueprints,url_prefix='/owners')
app.register_blueprint(cats_blueprint,url_prefix='/cats')

larger-application- exemple/myproject/cats/views.py
# cats --> views.py
from flask import Blueprint,render_template,redirect,url_for
from myproject import db
from myproject.cats.forms import AddForm,DelForm
from myproject.models import Cat

cats_blueprint = Blueprint('cats',__name__,template_folder='templates/cats')

@cats_blueprint.route('/add', methods=["GET","POST"])
def add():
    form = AddForm()

    if form.validate_on_submit():
        name = form.name.data

        # add new cat to database
        new_cat = Cat(name)
        db.session.add(new_cat)
        db.session.commit()

        return redirect(url_for('cats.list'))

    return render_template('add.html',form=form)

@cats_blueprint.route('/list')
def list():
    cats = Cat.query.all()
    return render_template('list.html', cats=cats)

@cats_blueprint.route('/delete', methods=["GET","POST"])
def delete():

    form = DelForm()

    if form.validate_on_submit():
        id = form.id.data
        cat = Cat.query.get(id)
        db.session.delete(cat)
        db.session.commit()

        return redirect(url_for("cats.list"))

    return render_template('delete.html',form=form)

larger-application- exemple/myproject/owners/views.py
#myproject/owners/views.py
from flask import Blueprint,render_template,redirect,url_for
from myproject import db
from myproject.models import Owner
from myproject.owners.forms import AddForm

owners_blueprints = Blueprint('owners',__name__, template_folder = 'templates/owners')

@owners_blueprints.route('/add',methods=['GET','POST'])
def add():

    form = AddForm()

    if form.validate_on_submit():

        name = form.name.data
        cat_id = form.cat_id.data
        # add new owner to database
        new_owner = Owner(name,cat_id)
        db.session.add(new_owner)
        db.session.commit()

        return redirect(url_for('list_cat'))

    return render_template('add.html',form=form)

larger-application- exemple/myproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>Document</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
    integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous">
    </script>

</head>
<body>

    <nav clas='navbar navbar-expand-lg navbar-light bg-light'>

        <div class="collapse navbar-collapse" id="navbarNav">

            <a class="nav-item nav-link" href="{{url_for('index')}}">Home</a>
            <a class="nav-item nav-link" href="{{url_for('cats.add')}}">Add Cat</a>
            <a class="nav-item nav-link" href="{{url_for('cats.list')}}">List of Cats</a>
            <a class="nav-item nav-link" href="{{url_for('cats.delete')}}">Delete Cat</a>

        </div>
    </nav>

    {% block content %}

    {% endblock %}

</body>
</html>

larger-application- exemple/myproject/templates/home.html
{% extends 'base.html' %}

{% block content %}

<div class="jumbotron">

    <h1>Welcome</h1>
    <p>Please select one of the links from the nav bar.</p>

</div>

{% endblock %}